version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies"
    commit-message:
      prefix: "Dependencies"
    rebase-strategy: auto
    allow:
      - dependency-name: "tinacms"
      - dependency-name: "@tinacms/*"
    ignore:
      - dependency-name: "yup"
    groups:
      tinacms:
        patterns:
          - "@tinacms/*"
          - "tinacms"
